### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Ashaman-** [royneary/oshiya#3]
Only GCM and Ubuntu configured, no APNS.

On CentOS7
./oshiya 
Oshiya
config file: /etc/oshiya/oshiya.yml
setting component jid: <component_jid>
setting component password: <password>
DEBUG: in GcmBackend::send
DEBUG: in UbuntuBackend::send
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted (core dumped)

**Comment by LacieNat** [comment]
what is the cause of this error? I'm getting this too :(

**Comment by Ashaman-** [comment]
I think it expects APNS to be configured....
Edit: Closer inspection of the code has helped me discover that I had no idea what I was talking about here.

@LacieNat Have you had any luck getting it working?

**Comment by Ashaman-** [comment]
Fixed. Crash was occuring because the directory /var/run/oshiya/push.example.com did not exist. If running multiple hosts, a directory for each one must exist in /var/run/oshiya.
